networks:
  default:
    name: "makesport"

volumes:
  makesport-pg-data:

services:
  postgres:
    container_name: makesport-pg
    image: postgis/postgis:17-3.5
    ports:
        - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: makesport-db
    volumes:
      - makesport-pg-data:/var/lib/postgresql/data