<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL.NetTopologySuite" Version="9.0.4" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\MakeSport.Application\MakeSport.Application.csproj" />
      <ProjectReference Include="..\MakeSport.Domain\MakeSport.Domain.csproj" />
    </ItemGroup>

</Project>
