<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Serilog" Version="4.3.1" />
        <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
        <PackageReference Include="Serilog.Exceptions" Version="8.4.0" />
        <PackageReference Include="Serilog.Settings.Configuration" Version="10.0.0" />
        <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
        <PackageReference Include="Serilog.Sinks.Debug" Version="3.0.0" />
        <PackageReference Include="Serilog.Sinks.Seq" Version="9.1.0" />
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="10.1.1" />
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.1.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\MakeSport.Application\MakeSport.Application.csproj" />
      <ProjectReference Include="..\MakeSport.Contracts\MakeSport.Contracts.csproj" />
      <ProjectReference Include="..\MakeSport.Infrastructure.Postgres\MakeSport.Infrastructure.Postgres.csproj" />
    </ItemGroup>

</Project>
