// <auto-generated />
using System;
using FileService.Infrastructure.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FileService.Infrastructure.Postgres.Migrations
{
    [DbContext(typeof(FileServiceDbContext))]
    partial class FileServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FileService.Domain.Assets.MediaAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("key");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("asset_type")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("media_assets", (string)null);

                    b.HasDiscriminator<string>("asset_type").HasValue("MediaAsset");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("FileService.Domain.Assets.ImageAsset", b =>
                {
                    b.HasBaseType("FileService.Domain.Assets.MediaAsset");

                    b.HasDiscriminator().HasValue("image");
                });

            modelBuilder.Entity("FileService.Domain.Assets.VideoAsset", b =>
                {
                    b.HasBaseType("FileService.Domain.Assets.MediaAsset");

                    b.HasDiscriminator().HasValue("video");
                });

            modelBuilder.Entity("FileService.Domain.Assets.MediaAsset", b =>
                {
                    b.OwnsOne("FileService.Domain.MediaData", "MediaData", b1 =>
                        {
                            b1.Property<Guid>("MediaAssetId");

                            b1.Property<int>("ExpectedChunksCount")
                                .HasJsonPropertyName("expected_chunks_count");

                            b1.Property<long>("Size")
                                .HasJsonPropertyName("size");

                            b1.HasKey("MediaAssetId");

                            b1.ToTable("media_assets");

                            b1
                                .ToJson("media_data")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("MediaAssetId");

                            b1.OwnsOne("FileService.Domain.ContentType", "ContentType", b2 =>
                                {
                                    b2.Property<Guid>("MediaDataMediaAssetId");

                                    b2.Property<string>("Category")
                                        .IsRequired()
                                        .HasJsonPropertyName("category");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasJsonPropertyName("value");

                                    b2.HasKey("MediaDataMediaAssetId");

                                    b2.ToTable("media_assets");

                                    b2.WithOwner()
                                        .HasForeignKey("MediaDataMediaAssetId");
                                });

                            b1.OwnsOne("FileService.Domain.FileName", "FileName", b2 =>
                                {
                                    b2.Property<Guid>("MediaDataMediaAssetId");

                                    b2.Property<string>("Extension")
                                        .IsRequired()
                                        .HasJsonPropertyName("extension");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasJsonPropertyName("name");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasJsonPropertyName("value");

                                    b2.HasKey("MediaDataMediaAssetId");

                                    b2.ToTable("media_assets");

                                    b2.WithOwner()
                                        .HasForeignKey("MediaDataMediaAssetId");
                                });

                            b1.Navigation("ContentType")
                                .IsRequired();

                            b1.Navigation("FileName")
                                .IsRequired();
                        });

                    b.Navigation("MediaData")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
